### ISSUE TITLE
Bug with the chat : too many ghosts / non existing person in there

### ISSUE THREAD

**Issue by micbuffa** [ALXRSS/WebRTC-Conf#46]
We tried with two persons the version at visio.gexsoft.com, as soon as we entered the room, I found ghosts of people I created yesterday.... They were still in the session...

HOW CAN WE REALLY LEAVE A ROOM ? You must monitor disconnections from the server and remove leaving users from the list of people connected.

**Comment by Desiderius77** [comment]
Yes I have observed that too ! There are ghosts in the rooms ! May be clear deconnection button is necessary

**Comment by micbuffa** [comment]
No, with socket.io it's easy to detect disconnexions, it's a pure software problem in your code. See for example how I manage disconnections in this example: http://miageprojet2.unice.fr/Intranet_de_Michel_Buffa/Cours_Web_2.0_%2f%2f_HTML5_%2f%2f_JS_2015-2015/TP_WebSockets_%2f%2f_Rabat_2014-2015

**Comment by polskataga** [comment]
Can you explain where you found ghosts of people ? In the chat ? in the list of participants ? displayed videos ? other ?

**Comment by micbuffa** [comment]
Yes, I made some tests in the morning with user John + user Michel. Then I closed the tabs and made some other demos with user Toto and user RHAAAA, then I closed the tabs and made some other demos with other users.... After a while (maybe Two hours, but I never shit down the browser, and I had no tabs open on visio.gexsoft.com, then I tried again with two new users, and when I opened the chat room I could see all the previous users + what had been said. Like if the room was never closed. 

I re-created every time a room with the same name.

**Comment by polskataga** [comment]
Ok, there is a misunderstanding.

Each time a person is connecting to WebRTC-Conf, we load the conversation recorded in the mainRoom.txt from the last session.

In this case, we will continue to record the conversation in the file mainRoom.txt but no more load this one in the chat.

**Comment by micbuffa** [comment]
Ok, my fault then, no I think it's a good thing to record and restore the previous logs from a room's chat.
BTW : the url is always /room/main is it normal ?

**Comment by micbuffa** [comment]
The URL should reflect the room so that we can send it by copy and paste, can't we?
I created a room called W3C and then I see the chat log from mainRoom.txt ? of from W3CRoom.txt ? We need a log per room.
And once created, apparently a room still exists even if everybody leaves the room...

The workflow of room creation / persistence / sharing is really not clear for me in your work... Can you explain, what is happening if I create a room called W3C, invite two persons, I leave, everybody leaves, does the room still exists, is it still displayed as a button (no apparently), is the chat history available (apprently yes), do you really manage multiple rooms (apparently not really), does the url reflects the one of the room (apparently no).

I'd like clear explanations of the room lifecycle.

**Comment by polskataga** [comment]
Exactly. we have created the corresponding issue for this : https://github.com/ALXRSS/WebRTC-Conf/issues/10

We really would like to do this ! Besides, we are able to create different room but not yet in different URL
